# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("FileDownloader")
        Form.resize(807, 522)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(160, 50, 491, 141))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 110, 72, 15))
        self.label.setObjectName("label")
        self.btn_Download = QtWidgets.QPushButton(Form)
        self.btn_Download.setGeometry(QtCore.QRect(480, 220, 111, 41))
        self.btn_Download.setObjectName("btn_Download")
        self.btn_inputFile = QtWidgets.QPushButton(Form)
        self.btn_inputFile.setGeometry(QtCore.QRect(190, 220, 111, 41))
        self.btn_inputFile.setObjectName("btn_inputFile")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(160, 300, 491, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        self.btn_inputFile.clicked.connect(Form.inputFileClicked) # type: ignore
        self.btn_Download.clicked.connect(Form.downloadFileClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "URL:"))
        self.btn_Download.setText(_translate("Form", "Download"))
        self.btn_inputFile.setText(_translate("Form", "Open File"))